spring.application.name=UrlShortner

# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/UrlShortner?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=221018

# Hibernate/JPA Settings (Optional, but highly recommended)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

